### PR TITLE
Madmax test

### PR DESCRIPTION
**Pull request by Madmaxvoltron**
a test and sum other special stuff
please add it

### CODE REVIEW

**Comment by Madmaxvoltron** [comment]
it has beta website in it

**Comment by LemurDev** [comment]
As the instructions say, please commit it to the `dev` branch instead of main. Main is meant for really important updates and final releases. Dev is meant for things like this.

**Comment by LemurDev** [comment]
Also, why is there a random `text.txt` file?

**Comment by Madmaxvoltron** [comment]
cuz last time i pushed the i could not pull it to this project but so i added a random txt so there was a update so i could add commit push pull

**Comment by LemurDev** [comment]
Could you please recommit but without the random text file?

**Comment by Madmaxvoltron** [comment]
okay

**Comment by LemurDev** [comment]
Thank you!

**Comment by Madmaxvoltron** [comment]
normaly its done now

**Comment by LemurDev** [comment]
I still see the `test.txt` file in your commit and you have it still going to the **main** branch instead of **dev**.

**Comment by Madmaxvoltron** [comment]
what command to fix it

**Comment by LemurDev** [comment]
Once you remove the file and push it to the branch `madmax-test`, this pull request should update with the new changes.

**Comment by Madmaxvoltron** [comment]
i did it check ur discord

**Comment by Madmaxvoltron** [comment]
i did it
but is it updated now

**Comment by Madmaxvoltron** [comment]
one more thing how to change this to dev branch

**Comment by williamrhayes** [comment]
Looks like you've got the hang of PRs @Madmaxvoltron , closing this one out.

**Comment by Madmaxvoltron** [comment]
@williamrhayes please don't close this one and accept it cuz it has the website code in it

**Pull request closed without merging**
