### PR TITLE
website

### PR DESCRIPTION
**Pull request by Madmaxvoltron**
# the website
## all u need to know

it has these things
- home
- fighters
and thats it didint code much

### CODE REVIEW

**Comment by Madmaxvoltron** [comment]
i added the favicon to it

**Comment by Madmaxvoltron** [comment]
its a start of bet history code at home screen

**Comment by Madmaxvoltron** [comment]
could you guys please accept this pull request

**Comment by Madmaxvoltron** [comment]
@williamrhayes this update has the main CSS file in it so please try it out so i can learn from it

**Comment by Madmaxvoltron** [comment]
added a credits.html for all who have currently been contributing to the project

**Comment by williamrhayes** [comment]
Needs to follow project format to match with backend. Please pull from the main branch and try again. Thank you.

**Pull request closed without merging**
